### ISSUE TITLE
ffmpeg unrecognized? 

### ISSUE THREAD

**Issue by Sonny-Crockett** [chrisbenincasa/tunarr#1019]
Using the development build with intel GPU support. Confirmed ffmpeg is in the correct path. (usr/bin/ffmpeg) 

The regular build seems to work, so wondering what I am doing wrong. 

My unraid server with Plex works with the intel GPU so I know thats mapped and working. 

![image](https://github.com/user-attachments/assets/010fa2a7-3ba8-41d3-9ea3-c0bcf45d0581)

**Comment by chrisbenincasa** [comment]
i think this is the same question from the discord? going to duplicate my reply here -- 

> This is ok an expected, but it’s a weird experience admittedly. Tunarr packaged a custom version of ffmpeg in that build but the code to check versions only recognizes the numeric versions. Tl;dr it’s fine and expected

We should allowlist this version because this question has come up a few times.

**Comment by Sonny-Crockett** [comment]
Thank you!
