### ISSUE TITLE
Plex token redacted even though token is valid, Tunarr cannot stream any filler content

### ISSUE THREAD

**Issue by ameturpoet** [chrisbenincasa/tunarr#1033]
[tunarr_log.txt](https://github.com/user-attachments/files/18278030/tunarr_log.txt)

I get this error which is crashing my Tunarr channels when switching to a new video in the queue - Tunarr claims the token is invalid and crashes the stream, but the token is still correct. After that, I see a stream halted error. After this crash happened once, now all channels fail to load with a "Could not tune the channel" error or a "This stream is facing technical issues" error, and now I can't stream anything, even after a restart of Tunarr.

**Comment by ameturpoet** [comment]
It seems like this is primarily an issue for loading filler videos - regular programming seems to work fine for the most part.

**Comment by Chh2tx** [comment]
The plex token is always redacted in the logs, even when valid, for security. So it showing as 'redacted' isn't an error itself as I understand it.

Now for the other 404s, I experienced what I believe is this exact error when items from my library had changed, I was doing some maintenance and renaming/replacing some library items. My Plex library had not yet updated to scan and update file paths. Thus when Tunarr went to Plex to try to play these items, they fail and 404 as they are not at the prior filename/path. It's also a similar error logged regarding thumbs IIRC when adding media/view collections and there is no poster set, as Tunarr cannot see/use the one Plex autogenerates, so the thumb entries are likely just a distraction in the logs.

This entry though, error code 254 is an ffprobe file not found, indicating the path or file name doesn't exist or is problematic? I'd double check your library, file path and/or naming scheme.

2024-12-30T13:44:01.503Z [error]: Error playing video {"code":254,"cmd":"/usr/bin/ffmpeg -hide_banner -threads 4 -fflags +genpts+discardcorrupt+igndts -loglevel warning -readrate 1.0 -ss 0 -i /commercials/00s Movies/00s Movies S1E60 - Rugrats Go Wild (2003) Trailer #1 _ Movieclips Classic Trailers.mkv

I'm successfully using Tunarr for filler videos that I maintain in a separate plex library for those.

**Comment by chrisbenincasa** [comment]
@Chh2tx is correct here - the REDACTED is simply for logs and the error code 254 from ffmpeg implies that the input file, in this case `/commercials/Cartoon Network/Cartoon Network Bumpers S1E153 - Cartoon Network City In The Morning  - CN Spain Bumper.mp4` is not found (or visible) from Tunarr

**Comment by ameturpoet** [comment]
I think it might be because I set the source to Direct instead of Network, and the filler is stored on the SSD instead of the HDD - I'm waiting for filler to appear so I can test this theory, but it would be super useful to allow multiple path mappings for Direct mode

**Comment by chrisbenincasa** [comment]
Would be great to get multiple replace paths, definitely open a feature request. Similarly, having these all configured per source is tracked here https://github.com/chrisbenincasa/tunarr/issues/677
