### ISSUE TITLE
Convert all settings pages to use react-form

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#105]
- [x] Convert all settings pages to use react-form.  Reciew react-form implementation in channel editing page.
- [x] Verify all settings are properly working with helper text where necessary

**Comment by chrisbenincasa** [comment]
Did FFMPEG in #134

**Comment by markdavella** [comment]
Fixed XMLTV in https://github.com/chrisbenincasa/tunarr/pull/237

**Comment by markdavella** [comment]
Did HDHR in https://github.com/chrisbenincasa/tunarr/pull/239
