### ISSUE TITLE
Create Welcome Screen for New Users

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#12]
Create a welcome screen with a checklist for new users.

Get started with Tunarr:
1. Connect your Plex account (include direct link to connect it right there)
2. Create a Channel
3. Add Programming to a channel

Screen can be manually dismissed or will automatically dismiss when checklist is completed.

The goal here to make a seamless onboarding experience so there is no confusion on what users need to do to get started

**Comment by chrisbenincasa** [comment]
Should probably include some migration ui if they are coming from dizque
