### ISSUE TITLE
Add default messaging when there is no guide gata

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#154]
(Just a loading indicator, hard to see in screenshot)
<img width="1606" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/0dfe4594-517e-42a0-935c-ce406845e604">

After fetch fails:
<img width="593" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/61f5768c-32ee-43ad-ae83-6557b5d69352">

**Comment by chrisbenincasa** [comment]
Think https://github.com/chrisbenincasa/tunarr/pull/387 solved this but correct me if i'm wrong!
