### ISSUE TITLE
Improve Channel page messaging when no channels exist

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#155]
Fetching:
<img width="654" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/fc18cfee-dcda-42b3-9e98-d91d80161244">

After fetch fails:
<img width="577" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/7fa3c86a-028a-46c9-b40a-d70cb3e390ee">

**Comment by chrisbenincasa** [comment]
Looks fixed, nice!

<img width="1552" alt="Screenshot 2024-05-30 at 7 36 30 AM" src="https://github.com/chrisbenincasa/tunarr/assets/1640671/46a038be-56d9-4971-bbaa-9fccba0c8037">
