### ISSUE TITLE
Add day of week input to weekly time schedule

### ISSUE THREAD

**Issue by chrisbenincasa** [chrisbenincasa/tunarr#19]

**Comment by markdavella** [comment]
@chrisbenincasa has this been resolved? Not sure which input this is referring to exactly but I thinkkk they all include dates but correct me if I am wrong!

**Comment by chrisbenincasa** [comment]
Ah sorry, I was referring to the time slot scheduler. This was tracking implementing switching between daily / weekly schedules, which has been implemented now. Though we probably will want to tackle #102 at some point to make this better.
