### ISSUE TITLE
Add GitHub link to top nav

### ISSUE THREAD

**Issue by chrisbenincasa** [chrisbenincasa/tunarr#190]

**Comment by bottlewook** [comment]
Hi! I'll do this. assign to me.

**Comment by chrisbenincasa** [comment]
Thanks!

**Comment by chrisbenincasa** [comment]
We can use the MUI icon for Github

<img width="603" alt="Screenshot 2024-03-19 at 11 10 45 PM" src="https://github.com/chrisbenincasa/tunarr/assets/1640671/e240878f-7323-4ae4-ae10-2f7d50486999">

**Comment by boioboi16** [comment]
Hey, I'm new to open source. also, is this how you wanted it to be?
![tunarr](https://github.com/chrisbenincasa/tunarr/assets/55227143/8eff88b7-291d-41ae-8124-0ccb20f6834f)

**Comment by chrisbenincasa** [comment]
Looks good!

**Comment by chrisbenincasa** [comment]
Completed with https://github.com/chrisbenincasa/tunarr/pull/208
