### ISSUE TITLE
[Bug]: Consistent sizing of grid images when results are limited

### ISSUE THREAD

**Issue by chrisbenincasa** [chrisbenincasa/tunarr#209]
### What happened?

When we have <1 normal row of images they get huge

<img width="750" alt="Screenshot 2024-03-24 at 6 15 18 PM" src="https://github.com/chrisbenincasa/tunarr/assets/1640671/32d81856-2954-4c6b-852a-cbd37f397eaa">

### Version

current

**Comment by markdavella** [comment]
This is fixed with some of the newer changes to the grid.

Screenshot:
<img width="1545" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/b36cdd0f-8f53-4cb2-92cd-8e7e9a73e7c4">
