### ISSUE TITLE
[Bug]: Background color gets cutoff at bottom of container

### ISSUE THREAD

**Issue by chrisbenincasa** [chrisbenincasa/tunarr#230]
### What happened?

![Screenshot from 2024-04-03 12-27-27](https://github.com/chrisbenincasa/tunarr/assets/1640671/930f5ce3-b19a-4729-97fa-8939a743b95b)

### Version

0.1.0

**Comment by markdavella** [comment]
@chrisbenincasa yea, this was me!  I had to comment out the 100vh height on `<main>` because `scrollTo()` doesn't work with 100vh backgrounds.  I plan to find a workaround to this!
