### ISSUE TITLE
Jellyfin source library support

### ISSUE THREAD

**Issue by chrisbenincasa** [chrisbenincasa/tunarr#24]

**Comment by binarygeek119** [comment]
just to addon to this, emby support should be easy. as a few projects ive seen can just work with little tweaking from emby. not that i need emby support as ive switched to jellyfin. jellyseerr was able to work with emby just fine but did needa little bug fixed that was related to a slightly different url path.

**Comment by ghzgod** [comment]
"Access your channels by adding the spoofed Tunarr HDHomerun tuner to Plex, Jellyfin, or Emby. Or utilize generated M3U files with any 3rd party IPTV player app."

I don't see Jellyfin on the frontend setup page, Is Jellyfin implemented on the backend somewhere?

**Comment by chrisbenincasa** [comment]
Jellyfin is not implemented as a source yet, but you can add your channels (backed by Plex) to Jellyfin as a Live TV source: https://jellyfin.org/docs/general/server/live-tv/setup-guide/

We hope to start implementation of Jellyfin as a programming source soon, though!

**Comment by ghzgod** [comment]
Awesome thank you!

**Comment by RealBradCool** [comment]
how long is this complete

**Comment by chrisbenincasa** [comment]
This is in progress right now. You can follow https://github.com/chrisbenincasa/tunarr/pull/633 for updates on the implementation. There is no ETA right now. So far the following things are implemented:

- Adding jellyfin servers as a source
- UI for browsing your JF libraries 
- Selecting media to add to channels

What's left (might not be a complete list)
- Saving JF media to channels
- Streaming implementation 
- Assorted another cleanup 

I'd say we're still a bit away, but making solid progress

**Comment by RealBradCool** [comment]
um its draft could need fixed and says failed

**Comment by chrisbenincasa** [comment]
Yes I understand it's a draft. It's unfinished work that I push to continuously.

**Comment by RealBradCool** [comment]
hold on maybe i could help
