### ISSUE TITLE
Top bar XMLTV link is dead

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#252]
XMLTV link goes here:
http://localhost:8000/api/xmltv.xml

Just says "error"

**Comment by chrisbenincasa** [comment]
Is there a XML path error when you start your server? it's probably trying to load your file from the wrong path (this is in one of the settings JSON files). My XMLTV loads fine.

**Comment by chrisbenincasa** [comment]
This is probably related to #186

**Comment by chrisbenincasa** [comment]
Pull down https://github.com/chrisbenincasa/tunarr/commit/01fe14a6edc7eed697dc62aae433a697e336aeba and lmk if it fixes your issue

**Comment by markdavella** [comment]
Pull down latest and this is working without issue!  Nice work!
