### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by chrisbenincasa** [chrisbenincasa/tunarr#255]
We need a new logo. Obviously something TV related. The existing logo is branded dizqueTV.

**Comment by chrisbenincasa** [comment]
Looks amazing!

**Comment by markdavella** [comment]
Just dropping the logo Figma file here as a backup
[Tunnar Logo.fig.zip](https://github.com/chrisbenincasa/tunarr/files/14979648/Tunnar.Logo.fig.zip)
