### ISSUE TITLE
Improve UX for Adjust Scheduling tool

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#278]
Note: We should also update "fast forward" to move forward, I know its currently in parity with DTV but it just doesn't make sense.

<img width="1267" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/e4d83f3b-4027-4159-aa8b-d2d5647f9feb">

**Comment by chrisbenincasa** [comment]
Totally agree

**Comment by chrisbenincasa** [comment]
Fixed in #311 311
