### ISSUE TITLE
Implement Balance Media

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#290]
Balance Media still needs to be implemented, both manual and automatic. 

<img width="1071" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/3b207409-c652-41d3-ba55-fbefd06551a1">

**Comment by chrisbenincasa** [comment]
We can reuse the slider logic I have on the Channel Flex Edit + Random slots pages for the weights here

**Comment by chrisbenincasa** [comment]
Was looking at this in DTV again... do we want this functionality? In my tests it always seems to totally mess up my channels and create weird results.
