### ISSUE TITLE
[Bug]: web ui doesn't work properly in docker

### ISSUE THREAD

**Issue by jasongdove** [chrisbenincasa/tunarr#318]
### What happened?

Doesn't load `/web` by default:

- run: `docker run -it --rm -p 8000:8000 tunarr`
- open http://localhost:8000/
- result: `{"message":"Route GET:/ not found","error":"Not Found","statusCode":404}`

Refresh doesn't work outside of `/web`:

- open http://localhost:8000/web
- click on any other page (like settings)
- press F5 to refresh
- result: `{"message":"Route GET:/web/settings/general not found","error":"Not Found","statusCode":404}`

### Version

0.1.0

### What browser did you experience the the problem on?

Firefox 124.0.2

### What operating system are you using?

Linux

**Comment by chrisbenincasa** [comment]
Interestingly, on a fresh pull I was able to hit the UI fine. After killing the container and restarted, I could reproduce the issue. I'll look into this.

**Comment by chrisbenincasa** [comment]
Ahhh... ok I have an interesting development -- on a fresh pull, if I attempt to load anything other than `/web`, I'll get the error (e.g. `/web/welcome`). Alternatively, hitting just `/web` loads the page fine and then the browser routing takes over and all is well:

![image](https://github.com/chrisbenincasa/tunarr/assets/1640671/78270f4b-4873-4132-aa9d-6ba3ecf032fc)


Opening a separate issue for the lack of ffmpeg in the base container, though.

**Comment by chrisbenincasa** [comment]
So far I think we need a wildcard route matcher here:

https://github.com/chrisbenincasa/tunarr/blob/b0690f2310ad3a2b717b1790f7e6bcb31db58c2c/server/src/server.ts#L283

It'll all point to the base index.html and let react-router take over from there. I'll test it out.

**Comment by chrisbenincasa** [comment]
We can probably add the default / to go to /web/index.html as well without issue (for the full stack container)

**Comment by chrisbenincasa** [comment]
Just merged the fix here and kicked off a Docker build: https://github.com/chrisbenincasa/tunarr/actions/runs/8739088661

**Comment by jasongdove** [comment]
> We can probably add the default / to go to /web/index.html as well without issue (for the full stack container)

Will this be addressed separately? The second item is resolved (loading something like `/web/settings/general` directly), but first item (the default `/` route) still gives a 404:

```shell
% xh http://tunarr:8000
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 72
Content-Type: application/json; charset=utf-8
Date: Thu, 18 Apr 2024 15:19:43 GMT
Keep-Alive: timeout=72
Vary: Origin

{
    "message": "Route GET:/ not found",
    "error": "Not Found",
    "statusCode": 404
}
```

**Comment by chrisbenincasa** [comment]
Serving web off of a non-prefixed path wasn't originally in the plan, but it's definitely something we can consider.

**Comment by chrisbenincasa** [comment]
Also sorry for the confusion on my comment - I was referring relative to the /web prefix (it was always my intent to keep web under the prefix). So /web, /web/, and /web/* should all work now. Plain / could work but was not something I looked into as part of the fix here

**Comment by jasongdove** [comment]
Ah, understood, thanks.

**Comment by chrisbenincasa** [comment]
Opened https://github.com/chrisbenincasa/tunarr/issues/329 to track that
