### ISSUE TITLE
[Bug]: Web API client is incorrectly configured for remote use

### ISSUE THREAD

**Issue by jasongdove** [chrisbenincasa/tunarr#324]
### What happened?

The API client is configured for localhost:8000, which won't work when tunarr is on another machine.

https://github.com/chrisbenincasa/tunarr/blob/8858db40d0cfc4b6e5908fffb9fcf744f33b9461/web/src/external/api.ts#L356

### Version

0.1.0

**Comment by chrisbenincasa** [comment]
Yea, this makes some assumptions at the moment -- namely that the webapp is running alongside the backend. I think there is a bit of a larger effort here to allow for configuring the endpoint client-side and saving that to your local storage (like we do with dark mode)

**Comment by jasongdove** [comment]
Maybe I'm not describing this correctly - when I view the guide page on a remote system, my browser tries to hit localhost:8000 for lineups, version, events and they all fail.

**Comment by jasongdove** [comment]
![bug-324](https://github.com/chrisbenincasa/tunarr/assets/1695733/cfbd7f38-ea1e-4c76-8e25-f52f2988dfb3)

**Comment by jasongdove** [comment]
> The API client is configured for localhost:8000, which won't work when tunarr is on another machine.

What I mean here is that the API client will not work when tunarr (backend and frontend - in my case one docker container) are on a different machine than the browser you use to access tunarr.

**Comment by chrisbenincasa** [comment]
Yep I understand! Opened https://github.com/chrisbenincasa/tunarr/issues/326 as a more generalized tracking bug.
