### ISSUE TITLE
Serve webapp on /index.html from backend

### ISSUE THREAD

**Issue by chrisbenincasa** [chrisbenincasa/tunarr#329]
Webapp is currently only served off the /web prefix. We should be able to take the same approach there and serve on the root path.

**Comment by jasongdove** [comment]
FWIW, I don't feel strongly about serving things with or without the /web prefix - just noting that the initial experience of deploying somewhere and opening the port in a browser to see a JSON 404 is probably not ideal. Maybe a simple redirect from `/` to `/web`?

**Comment by chrisbenincasa** [comment]
Yea it's a fair point! A redirect would probably suffice. I'm curious how difficult it would be to serve off of / anyway though...probably not too bad. I'll have a look into both once I clear up some other things. In the meantime it may something that some documentation could solve (we have a lot of work to do in that department anyway)

**Comment by chrisbenincasa** [comment]
Went the redirect route just to keep things simple.
