### ISSUE TITLE
Serve HLS segments from /hls to make relative playlist entries work properly

### ISSUE THREAD

**Issue by chrisbenincasa** [chrisbenincasa/tunarr#339]
When initiating the HLS stream off of /media-player/:id/hls/now, the relative segments are requested from '/media-player/:id/hls/segment' -- we should allow segments to be loaded from the /hls prefix in addition to the stream prefix. More context can be found at #334

**Comment by jasongdove** [comment]
I'm not sure that this is quite right - with the playlist itself moving up a level, the segments also need to move up a level to be at the same level as the playlist, which they are not currently.

```shell
mpv 'http://tunarr:8000/media-player/38f2c3df-3c05-4155-8e23-87762ded456b/hls'
[ffmpeg] Not detecting m3u8/hls with non standard extension and non standard mime type
[ffmpeg] Not detecting m3u8/hls with non standard extension and non standard mime type
Playing: http://tunarr:8000/media-player/38f2c3df-3c05-4155-8e23-87762ded456b/data00000.ts
[ffmpeg] http: HTTP error 404 Not Found
Failed to open http://tunarr:8000/media-player/38f2c3df-3c05-4155-8e23-87762ded456b/data00000.ts
```

**Comment by chrisbenincasa** [comment]
Interesting. This worked well for me in my local tests. I’ll take a look.

**Comment by chrisbenincasa** [comment]
I think there were just too many paths flying around here... let me know what you think of this: https://github.com/chrisbenincasa/tunarr/pull/346

We should just standardize on a single path and make sure all entrypoints to the stream align with that.

**Comment by chrisbenincasa** [comment]
https://github.com/chrisbenincasa/tunarr/pull/346 merged
