### ISSUE TITLE
New channel shows 'dirty changes' dialog after successful create

### ISSUE THREAD

**Issue by chrisbenincasa** [chrisbenincasa/tunarr#362]
Repro:

1. Start create a channel flow
2. Change a detail about the channel on the first settings page
3. Hit save

Expected:

Redirected back to channel list page

Actual:

'Proceed without saving' dialog pops up after successful save (due to auto-nav)

**Comment by markdavella** [comment]
I can't seem to repro this, I've tried changing all of the settings on the first settings page when creating a new channel but it still successfully auto-navs to channel page.  Are you still seeing this?

**Comment by markdavella** [comment]
@chrisbenincasa can you confirm if you are still seeing this?  I haven't been able to repro and I just tested on my server Tunarr and it worked as expected.  Let me know if there are updated repro steps!

**Comment by chrisbenincasa** [comment]
Can't repro anymore!
