### ISSUE TITLE
Delayed Default State for Empty Channels Page

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#371]
Fresh install shows this for about 5 seconds

<img width="1600" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/86771a08-03bd-4d29-a0cd-4113a9153a5c">

Then this:
<img width="1616" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/7d7274bf-48da-4418-b2e7-b8760a4ea996">

Need to investigate why its so delayed to show that

**Comment by chrisbenincasa** [comment]
I can't seem to reasonably repro this

**Comment by markdavella** [comment]
This is working just fine for me now on the server.  I think this is likely related to my backend URL being incorrect and it was just a network call that was blocking.
