### ISSUE TITLE
XMLTV Default State

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#373]
Need a default state to indicate that user needs to connect Plex before they can see XMLTV settings

<img width="783" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/07b2402e-3c52-410c-9451-e9720424327e">

**Comment by chrisbenincasa** [comment]
I think the network error here was from the misconfigured backend URL - XMLTV settings should not depend on Plex servers

**Comment by markdavella** [comment]
Yea, just confirmed all is good on my end after the backend URL update!
