### ISSUE TITLE
FFMPEG Threads Field Turns Blue on change

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#384]
<img width="654" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/4d7ad790-18df-44d2-a42b-76a5fc7fded5">

**Comment by chrisbenincasa** [comment]
lol this is the best bug

**Comment by chrisbenincasa** [comment]
Tried to repro this earlier this morning but I couldn't

**Comment by markdavella** [comment]
Looks like it's a browser specific thing.  Chrome is overriding the background color when a user uses auto-fills using a previously selected value.  In this case I used the dropdown next to the field to choose a number value I had previously selected.  Assuming they do this to ensure users know which fields were just auto-filled.  Closing this!

<img width="325" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/775b8ed2-94c0-408c-b2aa-f2956a494a06">
