### ISSUE TITLE
Modal should handle non-content more gracefully

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#388]
Need to figure out what should be displayed for non-content modals (flex, redirects, etc)

<img width="1211" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/7c74c1dd-1b2a-4255-b239-fceb154af7a5">

**Comment by chrisbenincasa** [comment]
For flex I think we should just disable clicks. Redirects should render directly in the guide (i.e. they will show what is currently playing at that time on the redirect channel), so that should work
