### ISSUE TITLE
Add Helper Text for Channel Group

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#391]
We should add Helper Text to describe what "Channel Groups" are for and how they are used.  For new users just starting out this field may stump them and delay them creating their first channel

<img width="1227" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/0a9e18c7-a84a-4408-b24b-24ac2bc33a04">

**Comment by chrisbenincasa** [comment]
Original DTV helper text says

> This is used by iptv clients to categorize the channels. You can leave it as dizqueTV if you don't need this sort of classification.
