### ISSUE TITLE
Unraid Application

### ISSUE THREAD

**Issue by adrianipopescu** [chrisbenincasa/tunarr#434]
**Is your feature request related to a problem? Please describe.**
Have the ability to easily install the application on Unraid Docker

**Describe the solution you'd like**
Build a template and publish it on the Unraid CA store

**Describe alternatives you've considered**
Manual deployments in Podman on a VM / Docker CLI, but not fun and it isn't persisted.

**Additional context**
Could be very useful to also bring more community attention / contributions to the project.

**Comment by chrisbenincasa** [comment]
Thanks for the suggestion! I'm going to mark this as "help wanted" for now, since (if I'm reading correctly) getting the necessary generated config to submit your app for approval to the CA suggests that you must use Unraid (https://forums.unraid.net/topic/57181-docker-faq/#comment-566084). That said, I'm sure there are plenty of examples out there that we could cargo cult off of; but we'd still appreciate any help here!

**Comment by nwithan8** [comment]
I write a lot of Unraid templates, and came here specifically to figure out how to set up this container to write a template for it. Running into a Node issue inside the container following the [dev compose file](https://github.com/chrisbenincasa/tunarr/blob/main/docker/dev.compose.yaml). If you have a better compose stack that I can follow, I can translate that into an Unraid template and get this on the Unraid CA store immediately.

**Comment by chrisbenincasa** [comment]
Thanks! That dev compose is a WIP (and it's meant for running the dev app in a local container for debugging, etc). 

The compose file in the docs is probably closer to what you want: https://tunarr.com/getting-started/setup/

I'm not sure how this translates to Unraid templates, but there are a couple options that are dependent on the user's personal setup (e.g. changing the image / runtime params for hw accel, adding in the dizquetv folder as a volume if they are migrating, exposed port etc):


Here is another example I just tested out locally
```docker.compose.yaml
version: '3.8'
services:
  tunarr:
    # image: chrisbenincasa/tunarr:edge
    # Uncomment along with runtime below to enable HW accel
    image: chrisbenincasa/tunarr:edge-nvidia
    container_name: tunarr
    ports:
      - 8088:8000
    # Uncomment if using the Nvidia container
    runtime: nvidia
    # volumes:
      # The host path is relative to the location of the compose file
      # This can also use an absolute path. 
      # 
      # Uncomment if migrating from dizquetv. Chnage the host path
      # to the location of your dizquetv "database"
      # - ./.dizquetv:/.dizquetv
```

**Comment by nwithan8** [comment]
> Thanks! That dev compose is a WIP (and it's meant for running the dev app in a local container for debugging, etc).
> 
> The compose file in the docs is probably closer to what you want: https://tunarr.com/getting-started/setup/
> 
> I'm not sure how this translates to Unraid templates, but there are a couple options that are dependent on the user's personal setup (e.g. changing the image / runtime params for hw accel, adding in the dizquetv folder as a volume if they are migrating, exposed port etc):
> 
> Here is another example I just tested out locally
> 
> ```miniyaml
> version: '3.8'
> services:
>   tunarr:
>     # image: chrisbenincasa/tunarr:edge
>     # Uncomment along with runtime below to enable HW accel
>     image: chrisbenincasa/tunarr:edge-nvidia
>     container_name: tunarr
>     ports:
>       - 8088:8000
>     # Uncomment if using the Nvidia container
>     runtime: nvidia
>     # volumes:
>       # The host path is relative to the location of the compose file
>       # This can also use an absolute path. 
>       # 
>       # Uncomment if migrating from dizquetv. Chnage the host path
>       # to the location of your dizquetv "database"
>       # - ./.dizquetv:/.dizquetv
> ```

Thanks, I'll test it out

**Comment by nwithan8** [comment]
Got it, needed to permanently mount `/tunarr/server/build/.tunarr`:

```
version: '3.8'
services:
  tunarr:
    image: chrisbenincasa/tunarr:edge
    container_name: tunarr
    ports:
      - 8088:8000
    volumes:
      - /mnt/user/appdata/tunarr/dizquetv_migration:/.dizquetv
      - /mnt/user/appdata/tunarr/data:/tunarr/server/build/.tunarr
```

Drafting up an Unraid template now.

**Comment by nwithan8** [comment]
<img width="219" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/17054780/37a1e603-9566-452b-8224-1693c2388f84">

Template is done and tested. Should be live in the Community Apps store in a few hours.

**Comment by chrisbenincasa** [comment]
Wow this is awesome! Thanks a ton! Curious, how will this handle different builds? Eventually, we'll have a stable image build (docker tag latest), then also this edge build, and perhaps a "next" build that has semi stable features. Can unraid expose different builds in the template for users to choose from?

**Comment by sharri46** [comment]
It seems the migration isn't working correctly with the current template. No migration is being initiated when being pointed to the dizquetv appdata folder

**Comment by nwithan8** [comment]
> ```yaml
> /mnt/user/appdata/tunarr/dizquetv_migration:/.dizquetv
> ```

@chrisbenincasa The template currently maps dizqueTV's parent folder to `/.dizqueTV` inside the container as read-only. Does it need to be read-write?

**Comment by chrisbenincasa** [comment]
No, Tunarr doesn't require write permissions to the `.dizquetv` directory. The migration is read-only

**Comment by nwithan8** [comment]
Then I'm confused about why the migration may not be running.

**Comment by josway** [comment]
Having the same issue with the migration. Not seeing that running on my new install as well.

**Comment by chrisbenincasa** [comment]
Hmm, perhaps something regressed. I'll try either later today or tomorrow morning. Though I won't be able to test the unraid setup specifically.

**Comment by chrisbenincasa** [comment]
Oh one other thing... it could be because the Tunarr database directory exists already. The migration is skipped in that case in order to not overwrite any existing Tunarr data (subsequent runs). Does the unraid setup pre create this directory or something? Maybe we need a better method of tracking when to migrate (a db field).  

See the init db directory function in this file. 
https://github.com/chrisbenincasa/tunarr/blob/main/server/src/server.ts

**Comment by nwithan8** [comment]
> Oh one other thing... it could be because the Tunarr database directory exists already. The migration is skipped in that case in order to not overwrite any existing Tunarr data (subsequent runs). Does the unraid setup pre create this directory or something? Maybe we need a better method of tracking when to migrate (a db field).
> 
> See the init db directory function in this file. https://github.com/chrisbenincasa/tunarr/blob/main/server/src/server.ts

Yes, Unraid would create any paths that don't already exist, so it would precreate the associated `/tunarr/server/build/.tunarr` path: https://github.com/nwithan8/unraid_templates/blob/750fa251daa2762a9204824f9a76c969720e73d3/templates/tunarr.xml#L51

**Comment by chrisbenincasa** [comment]
Ah thanks for the context. That is most likely it then. Let me file an issue to capture this. This might be a little tricky since we try to the treat the whole directory as "one", even though it includes several files with different parts of the state. But so long as we have a universal marker for "first run" that works in all envs we should be good. I'll think on it.

**Comment by chrisbenincasa** [comment]
Opened #474 to track the full solution. It'll be the next thing I tackle.

**Comment by nwithan8** [comment]
Fresh install of the container on Unraid does seem to be processing the `.dizquetv` migration properly now.

(I have some bad settings in my old DizqueTV installation, so migration failed and the web UI didn't load as a result, but the migration DID trigger):

<img width="778" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/17054780/2e65d765-0377-43a0-bc8f-6c5b4760d49a">

**Comment by chrisbenincasa** [comment]
Huh... the legacy migrator doesn't attempt to verify the Plex settings, it'll just blindly migrate them. This is likely coming from some other data fixers that happen afterward. Are there any more details in the logs? Otherwise, can you rerun with debug logs enabled (easiest way is the LOG_LEVEL env var) and see where exactly that is failing? 

It's _probably_ the right thing that it failed outright by being unable to reach your configured Plex server, but we should discover why

**Comment by josway** [comment]
I had similar results where the migrator started, even processed channels and then Plex through a 404 and things locked up. I am seeing the UI Route is the issue but also seeing that on my DizqueTV container right now as well.

**Comment by chrisbenincasa** [comment]
@josway happy to look further if you provide some debug logs -- check out my previous comment on how.

**Comment by chrisbenincasa** [comment]
@nwithan8 - did you get your issue resolve? I'm surprised there are locations in the code where a Plex request would cause the server to not start. If you are still having issues I'd love to check out some debug logs.

**Comment by nwithan8** [comment]
> @nwithan8 - did you get your issue resolve? I'm surprised there are locations in the code where a Plex request would cause the server to not start. If you are still having issues I'd love to check out some debug logs.

I ended up just deleting old/dead/bad Plex servers from the dizqueTV config file. The migration then went smoothly, web UI loaded, everything good.

**Comment by josway** [comment]
@chrisbenincasa Same for me as with @nwithan8. Bad Plex Server data hung everything up. Once I fixed that all went smoothly.

**Comment by chrisbenincasa** [comment]
Gotcha, thanks! I'll try injecting some bad values and see if I can reproduce.

**Comment by nwithan8** [comment]
> @nwithan8 think we can call this complete now? Really appreciate the effort here!

Yeah, the Unraid template aspect seems to be working just fine. The migration stuff is unrelated to Unraid, so this ticket can be closed. Let me know if you release a new Docker branch and I'll update the template accordingly. Or feel free to open a PR: https://github.com/nwithan8/unraid_templates/blob/750fa251daa2762a9204824f9a76c969720e73d3/templates/tunarr.xml

**Comment by chrisbenincasa** [comment]
Awesome, sounds good! Thanks again!

**Comment by josway** [comment]
@nwithan8 looks like Unraid Blacklisted this template. Below is the error message. 

Default tag (:latest) does not exist on dockerHub
This application template has been blacklisted.

**Comment by chrisbenincasa** [comment]
That's a weird requirement!

**Comment by chrisbenincasa** [comment]
I can definitely start publishing the latest tag along with the edge tag. Eventually latest will point to stable releases, though. Just didn't want to confuse anybody by redefining the tag down the road

**Comment by nwithan8** [comment]
> @nwithan8 looks like Unraid Blacklisted this template. Below is the error message.
> 
> Default tag (:latest) does not exist on dockerHub This application template has been blacklisted.

Welp, that's going to be funt to try to get reversed: 
<img width="1282" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/17054780/54d23969-1fe7-4648-a16b-2749b49b1113">

I'll reach out to Squid once there is a latest tag and see if I can get that un-blacklisted.

**Comment by chrisbenincasa** [comment]
"latest" tag now exists in both Docker hub and ghcr

When the time comes to change what version "latest" points to (when we're more stable) I'll let you know so we can update the template description to mention the difference in the tags.
