### ISSUE TITLE
Channel lineup converted to single flex program

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#44]
This may just be a fragment of a recent update that won't happen again in the future, but just documenting here in case it's not.  After the recent update this morning my initial channel ("Channel 1") had its lineup and programming replaced in the guide with a single Flex item.  Screenshots below, you can see that the programming still exists on the channel itself but the guide is only returning a single flex item.

Guide showing Flex item (console log showing channelLineup):
<img width="1795" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/f848a6b9-2515-4353-b532-c060b69d73c2">

Programming within the channel itself:
<img width="1795" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/f5b9eb0a-3169-4a39-b922-6d207a97738c">

**Comment by chrisbenincasa** [comment]
this happened to me this morning i think - may wanna check what your guideMinimumDuration setting is on the channel. miine was high from some testing and it just melded everything into a single flex item
