### ISSUE TITLE
Error when saving existing channel ("FST_ERR_FAILED_ERROR_SERIALIZATION")

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#459]
Repro steps:
1.) Delete flex from existing channel (my test channel had nothing but flex, so i cleared it all out)
2.) Add any new content to replace it
3.) Save the channel

Results:

You get a 500

Logs attached:
[tunarr_tunarr-ix-chart-5c99654d56-th982_ix-chart (2).log](https://github.com/chrisbenincasa/tunarr/files/15489337/tunarr_tunarr-ix-chart-5c99654d56-th982_ix-chart.2.log)

**Comment by chrisbenincasa** [comment]
Fixed in https://github.com/chrisbenincasa/tunarr/commit/b269920318cacf2778965d1c19388726952cbda4

ongoing discussion in https://github.com/mikro-orm/mikro-orm/discussions/5627
