### ISSUE TITLE
Auto update media list based on new content added to plex channels

### ISSUE THREAD

**Issue by aferrar** [chrisbenincasa/tunarr#479]
**Is your feature request related to a problem? Please describe.**
Hi there, thanks for all your help in troubleshooting earlier and for your active work on this amazing project. I import my channels from channel lists in plex that are auto-generated by PMM/Kometa. It would be really awesome if the app could allow scheduling of this sort of import with like cron or something.

**Describe the solution you'd like**
Some sort of option to automatically refresh content for channel from plex channel on scheduled basis.

**Describe alternatives you've considered**
Not sure

**Additional context**
Not sure

**Comment by chrisbenincasa** [comment]
Hey! Thanks for the suggestion. I'm pretty sure this ask is covered by #15 and/or #18. Let me know if those don't match what you're asking for, though.

**Comment by chrisbenincasa** [comment]
Awesome! Stay tuned there. Hoping to make some progress soon.
