### ISSUE TITLE
"Select All" for Programming Channels

### ISSUE THREAD

**Issue by josway** [chrisbenincasa/tunarr#481]
Would be a nice quality of life to have a Select All option for media as you are populating a channel. 

I like to make Genre Channels for movies that may have a large quantity of movies in them randomly playing but currently having to select each individual movie is tough. The Filtering works beautifully and is awesome. Just need a way to pulling everything that us Filter once set. 

Let me know if I am missing something as well!

**Comment by chrisbenincasa** [comment]
This is a great idea. Thanks for the suggestion! We'll probably tackle this soon.
