### ISSUE TITLE
API does not return programs that started playing before the guide 'start' time

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#50]
It looks like the API currently returns programs that start between FROM and TO.  However, in some cases, like the Bluey episode in the screenshot below, the episode started before the FROM time but ends between FROM and TO.  This creates a situation where we don't have the episode to display so the first program is made to look artificially longer than the rest.  Even though the missing episode already ended, we should still show it since that time period is visible in the guide.

See first ep of Bluey:
<img width="1664" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/8832292a-9a41-40b2-93fd-60b0fe96de8a">

**Comment by chrisbenincasa** [comment]
I think we determined this was the issue with the min guide duration setting on the channel? I can't repro anymore

**Comment by markdavella** [comment]
Yea, this is a non issue now!
