### ISSUE TITLE
[Bug]: Need to change channel number in order to enable save button

### ISSUE THREAD

**Issue by aferrar** [chrisbenincasa/tunarr#502]
### What happened?

I am attempting to add thumbnail images to my channels and am unable to save the changes unless I change the channel number to an untaken channel, save the change, and then switch then channel back and re-save

### Version

0.1.0

### What browser did you experience the the problem on?

Safari

### What operating system are you using?

UnRAID Docker

**Comment by chrisbenincasa** [comment]
Ah yep I think I've seen this one before. @markdavella Can you take a look? We may have to just manually set the form to dirty for the thumb change since it's a special field

**Comment by chrisbenincasa** [comment]
Nvm - I see the issue. Opening a PR
