### ISSUE TITLE
[Bug]: Error writing backups to default directory in container

### ISSUE THREAD

**Issue by josway** [chrisbenincasa/tunarr#506]
### What happened?

Turned on the backups option last night, leaving all of the variables as default. Woke up this morning to the docker container stopped and the logs showing the below. Let me know if you want me to re-create with different log level.

### Version

0.1.0

### What operating system are you using?

Docker

### Relevant log output

```shell
2024-06-12T08:00:09.262Z [error]: Error creating backup 
    err: {
      "type": "Error",
      "message": "EIO: i/o error, scandir '//sys/kernel/slab'",
      "stack":
          Error: EIO: i/o error, scandir '//sys/kernel/slab'
      "errno": -5,
      "code": "EIO",
      "syscall": "scandir",
      "path": "//sys/kernel/slab"
    }
```

**Comment by chrisbenincasa** [comment]
Can you share your backup config? it is in the settings.json file

**Comment by josway** [comment]
Settings.json Backup config...

{"backup":{"configurations":[{"enabled":true,"schedule":{"type":"every","increment":1,"unit":"day","offsetMs":10800000},"outputs":[{"type":"file","outputPath":"","archiveFormat":"tar","maxBackups":3}]}]}


Same output on with Debug logging on.

2024-06-12T14:33:46.374Z [error]: Error creating backup 
    err: {
      "type": "Error",
      "message": "EIO: i/o error, scandir '//sys/kernel/slab'",
      "stack":
          Error: EIO: i/o error, scandir '//sys/kernel/slab'
      "errno": -5,
      "code": "EIO",
      "syscall": "scandir",
      "path": "//sys/kernel/slab"
    }

**Comment by chrisbenincasa** [comment]
Cool, thanks for posting. I guess the default empty path is causing some issues on Unraid. Either that, or there is an issue dealing with the temporary directory (where Tunarr works on the backup) within the Unraid container. Based on the log message though, I think it is the former. 

Can you try setting the output path to a path within your container and see if the issue persists?

**Comment by chrisbenincasa** [comment]
Ah wait a minute, if there are truly no other logs, then this might be happening sooner in the backup than I thought and could actually be a tmpdir issue... but I would still expect something else in the logs around [here](https://github.com/chrisbenincasa/tunarr/blob/tanstack-router/server/src/dao/backup/ArchiveDatabaseBackup.ts#L32-L44) or [here](https://github.com/chrisbenincasa/tunarr/blob/tanstack-router/server/src/dao/backup/ArchiveDatabaseBackup.ts#L54)

**Comment by josway** [comment]
Adding a directory path, allows it to create a backup successfully.

**Comment by chrisbenincasa** [comment]
Interesting. I'll do some testing. We may have to forcefully resolve the empty path relative to the process's cwd

**Comment by josway** [comment]
Sounds good. Agreed.

**Comment by chrisbenincasa** [comment]
Weirdly, I thought this was the default. Node CLI seems to show the same...

```
) ✗ node 
Welcome to Node.js v20.11.1.
Type ".help" for more information.
> const path = require('node:path')
undefined
> path.resolve("")
'/home/christian/Code/tunarr'
> process.cwd()
'/home/christian/Code/tunarr'
> 
```

**Comment by chrisbenincasa** [comment]
Within a container -- this doesn't look quite right. We should probably try and use the default config directory if we detect we're running in a container:

```
) ✗ docker run --rm -it --name tunarr --entrypoint /bin/bash chrisbenincasa/tunarr:latest
root@8a554d4bfdc4:/# node
Welcome to Node.js v20.14.0.
Type ".help" for more information.
> const path = require('node:path')
undefined
> path.resolve("")
'/'
> path.resolve(process.cwd())
'/'
```

**Comment by chrisbenincasa** [comment]
Interestingly the default settings in a fresh container seem to work for me:

```
2024-06-12T17:11:34.643Z [info] <>: Writing backup to /tunarr-backup-20240612_171134.tar
2024-06-12T17:11:38.231Z [info]: Successfully generated backup to /tunarr-backup-20240612_171134.tar
2024-06-12T17:11:38.231Z [info]: Task BackupTask ran in 3598.45 ms
```

with the backup generated:
```
root@f45432afe826:/# ls -la /tunarr*
-rw-r--r-- 1 root root 266752 Jun 12 17:11 /tunarr-backup-20240612_171134.tar
```

Perhaps this is something Unraid specific with how the root directory works in containers

**Comment by nwithan8** [comment]
This **could** potentially be due to a misconfigured PUID/PGID in the Docker container (which I just pushed out a fix for for the Unraid template, should be live in an hour). Previously, it was accidentally set to use 1001:1001 for file permissions. Now it should use 099:100 (nobody:users), which is the default for the Unraid file system.

**Comment by josway** [comment]
I made the change to PUID/PGID on my container and reset the backup settings. That seems to still trigger the same error as above.

If I assign an Output Path of "/backups" in Tunarr. The logs show it successfully creating a backup to "/tmp/tunarr-backup-XXXXXXHuQzWR". 

Can we have a variable in the Unraid Template for the backup output path that is mapped to a backup folder in the config?

**Comment by nwithan8** [comment]
Ah, I think I see the problem. The template for Unraid only maps `/tunarr/server/build/.tunarr` rather than just the root `/tunarr` directory, so anything written above that directory in the app doesn't make it to the host file system. That's my bad. @chrisbenincasa if you can confirm that mapping `/tunarr` from the container to the host would cover all permanent data storage, I can change the template real quick.

**Comment by chrisbenincasa** [comment]
Maybe we should mount /config instead? Or both? I can't think of immediate harm of mounting /tunarr, but fwiw there is code already that attempts to detect a container runtime and chooses /config as the default output for logs. Perhaps we could do the same by default for backups in a container. And in the future, maybe even the DB directory should be under that path (in containers). 

At the end of the day the backup path is configurable in the UI but we should try to provide a sane default. I think for containers that's generally thought to be /config. But I'm open to discussion

**Comment by chrisbenincasa** [comment]
Addressed the default empty path in docker here: https://github.com/chrisbenincasa/tunarr/pull/530

After that PR, an empty backup path within a docker container will write backups to /config/tunarr/backups

**Comment by nwithan8** [comment]
I have added `/config/tunarr/backups` as a mappable path in the Unraid template.

**Comment by chrisbenincasa** [comment]
Thanks!

**Comment by josway** [comment]
Just pulled the changes from this weekend and I'm not seeing this path addition to the Unread template. Maybe I am missing something?

**Comment by nwithan8** [comment]
> Just pulled the changes from this weekend and I'm not seeing this path addition to the Unread template. Maybe I am missing something?

The template only updates if you delete and re-add the app via the CA store (and specifically skip using the cached template in your system). This is independent of "updating" the template due to a new Docker image being available.

**Comment by josway** [comment]
Appreciate that. Didn’t know that.

**Comment by josway** [comment]
Rebuilt my container with the updated template. Mapped directories accordingly. Set the backup path two different times in Tunarr as both blank and as the default path typed out "/config/tunarr/backups". I am successfully saving a backup file but each time the container also crashes right after. Below debug log...


2024-06-17T18:22:39.114Z [debug] <>: Added entry to backup: channel-lineups/fef02f92-bef2-461f-944a-a31029b8b238.json
2024-06-17T18:22:43.431Z [error]: Error creating backup 
    err: {
      "type": "Error",
      "message": "EIO: i/o error, scandir '//sys/kernel/slab'",
      "stack":
          Error: EIO: i/o error, scandir '//sys/kernel/slab'
      "errno": -5,
      "code": "EIO",
      "syscall": "scandir",
      "path": "//sys/kernel/slab"
    }
2024-06-17T18:22:43.434Z [info]: Task BackupTask ran in 5303.83 ms


Also getting a random crash on startup that seems new without any errors in the logs. Happens after this line...

2024-06-17T18:28:47.248Z [debug]: Push event: Started building tv-guide at = 2024-06-17T13:28:47-05:00


Can open new bug reports for each of these if preferred.

**Comment by chrisbenincasa** [comment]
Hmmm yea, really not sure what's up there. Happy to look into it more with full logs. You can open a separate issue (ro Q&A discussion) for the other failure too.
