### ISSUE TITLE
[Bug]: Cannot add any media using Unraid container

### ISSUE THREAD

**Issue by Raki72** [chrisbenincasa/tunarr#507]
### Contact Details

ra_ki@freenet.de

### What happened?

When setting up a new channel, my Plex server shows in the list but there is no media I can add. 

![image](https://github.com/chrisbenincasa/tunarr/assets/47062002/2a0f857f-62dd-490c-ae8b-0fa1883b8dad)

### Version

0.1.0

### What browser did you experience the the problem on?

Firefox

### What operating system are you using?

Windows 11

**Comment by chrisbenincasa** [comment]
Best guess here is that there is some issue communicating with your Plex server from Tunarr, since it seems like it is unable to even show you the list of libraries within your server. Can you check the console logs in your browser (not Tunarr server) and see if there are any errors?

**Comment by chrisbenincasa** [comment]
Did you configure your Plex server URL to use HTTPS? It looks like the request is getting rejected because of that.

I think this is a configuration issue

**Comment by Raki72** [comment]
You are right. When I initially added my Plex server using the UI, there was a weird URL in there (something like https://192-168-7-2:ddfdcvdhjghjxcghcx:32400). So I changed it manually to https://192.168.2.7:32400 but it didn't work.

Now I changed it to http://192.168.2.7:32400 and it worked. 

Thanks!
