### ISSUE TITLE
[Bug]: Hardware Acceleration Options

### ISSUE THREAD

**Issue by salty2011** [chrisbenincasa/tunarr#510]
### Contact Details

mbrine@outlook.com

### What happened?

In the Tunarr webui > Settings > FFMPEG

The dropdown for Hardware Acceleration only shows Software (no GPU) despite confirm that the nvidia gpu has been correctly attached to container. Have confirmed gpu in container by checking /dev/ and /dev/dri and can see the the nvidia folders and renderD128 device

In my container config have the runtime environment set to nvidia and also have the uuid set in nvidia_visible_devices variable

### Version

0.1.0

### What browser did you experience the the problem on?

Edge 125.0.2535.92

### What operating system are you using?

Windows 11

**Comment by chrisbenincasa** [comment]
Can you confirm you are using the edge-nvidia container? the HW accel options are derived from ffmpeg output

**Comment by salty2011** [comment]
Just realised that the container I am using is just tunarr:edge, however further reading you also have tunarr:edge-nvidia

For context deployed via unraid apps, this doesnt show and edge-nvidia when deploying and the instruction dont indicate to switch to that container tag either

**Comment by chrisbenincasa** [comment]
cc: @nwithan8 who created the Unraid template

Sorry for the confusion!

**Comment by salty2011** [comment]
Nah all good, ill check that repo and see if I can submit and update to get that fixed

**Comment by salty2011** [comment]
oh, nope @nwithan8 had that in there, this is completely user error on my part. Sorry to waste everyone's time
