### ISSUE TITLE
[Bug]: Unraid Docker Not Finding Intel GPU 

### ISSUE THREAD

**Issue by Keatingfish** [chrisbenincasa/tunarr#512]
### Contact Details

monkstah@gmail.com

### What happened?

Loaded Tunarr. Have the /dev/dri piece in my extra params. Have the  modprobe in my config. IGPU is actively working as I have GPU-TOP and Plex installed. However in Tunarr it is not finding the Intel GPU at all and only sits with software inside the docker webui. 

### Version

Newest Docker Container

### What browser did you experience the the problem on?

Chrome, Plex App, Plex Web

### What operating system are you using?

Unraid

**Comment by chrisbenincasa** [comment]
Possibly the same as https://github.com/chrisbenincasa/tunarr/issues/510 ? Can you confirm you are using the edge-nvidia container?

**Comment by Keatingfish** [comment]
I am not. I am using 
![image](https://github.com/chrisbenincasa/tunarr/assets/125478046/5b469678-28cc-454e-a0e9-a7c1daadf201)

**Comment by Keatingfish** [comment]
I am not. I am using

[image: image.png]

**Comment by chrisbenincasa** [comment]
Yep that is the problem then. The "edge-nvidia" tagged container is required to use Nvidia hwaccel, as it includes a version of the ffmpeg binary compiled with the necessary Nvidia encoders/decoders.

**Comment by chrisbenincasa** [comment]
Sorry - seeing now you are talking about the Intel GPU. There is another container called "edge-vaapi" that you want, for the same reasons described about the Nvidia container.

**Comment by chrisbenincasa** [comment]
Some more info on the different containers: https://tunarr.com/getting-started/installation/#docker

Per #434, the vaapi container is available on Unraid: 
![image](https://github.com/chrisbenincasa/tunarr/assets/1640671/7c890f10-dd20-4bdd-b61c-c46151866657)

**Comment by Keatingfish** [comment]
I don't have an nvidia. I have an intel processor with IGPU.

**Comment by Keatingfish** [comment]
Also just saw your 2nd post. I'll try the vaapi.

**Comment by Keatingfish** [comment]
Thank you that solved the problem. Obviously loads a bit slow but thats the
dumb plex interaction. :) Appreciate ya

**Comment by chrisbenincasa** [comment]
Thanks! Glad to hear it's working! We're working on improving the experience with iGPUs (#389) so stay tuned there. Appreciate the compliments, we're working hard!

**Comment by Keatingfish** [comment]
I have one more question. The watch inside of Tunarr, how does that work
with unraid? When i try that it just stays blank and nothing loads

**Comment by Keatingfish** [comment]
disregard it must of been part of that alpha stuff. I got it to load no
issues once i switched to aac and then reran it

**Comment by chrisbenincasa** [comment]
It might've been AC3, yea. There should be a warning in the UI when you have AC3 chosen as your audio codec, as it generally won't work in the browser. However that usually manifests as a normal video but with no audio. Unsure about a non-playing video and how AC3 would fix that, but glad it's working for you!
