### ISSUE TITLE
Some Posters Failing with ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#542]
Hitting an issue where sometimes a poster won't load, however when I access the URL(copied from DOM) directly it loads without issue.

<img width="1212" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/8ce21b80-a504-4cf1-8980-90f3d9a6098c">

Additional info:

**Request Headers:**
GET /api/metadata/external?mode=proxy&asset=thumb&id=plex%7CATN%7C77&thumbOptions=%7B%22width%22%3A480%2C%22height%22%3A720%7D HTTP/1.1
Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Host: localhost:8000
Pragma: no-cache
Referer: http://localhost:5173/
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"

**Response Headers:**
HTTP/1.1 200 OK
vary: Origin
access-control-allow-origin: *
x-plex-protocol: 1.0
content-type: image/jpeg
connection: close
x-plex-content-original-length: 71689
x-plex-content-compressed-length: 71697
content-length: 71697
cache-control: max-age=259200
date: Tue, 18 Jun 2024 13:40:59 GMT

**Comment by chrisbenincasa** [comment]
Interestingly, I just noticed that sometimes the posters are cut off:

![image](https://github.com/chrisbenincasa/tunarr/assets/1640671/2fcada63-4cf4-4fb5-ae8b-8095c9f12ab1)

I wonder if that is related

**Comment by chrisbenincasa** [comment]
In this case they seemed to be returned that way:

![image](https://github.com/chrisbenincasa/tunarr/assets/1640671/00003d74-1dca-4c07-b2d2-e2e429780e1f)
