### ISSUE TITLE
[Bug]: Image path issue

### ISSUE THREAD

**Issue by josway** [chrisbenincasa/tunarr#547]
### What happened?

Probably another Unraid issue here...maybe an issue with using a reverse proxy? Sorry I'm not exactly sure. Getting the following mixed results. 

1. Thumbnail images can be successfully uploaded and accessed form the /config/images/uploads folder. 
2. Adding an image in the file structure in config/images results in a 404. If moved to the  /config/images/uploads folder it is accessible. 
3. Changing the URL for the fallback image to /images/generic-offline-screen.png results in the image being pulled from somewhere but I do not see that file in the folder structure. 

Not seeing it as a permissions issue on my end but let me know if it's an easy fix or if I should use the Uploads folder. 

### Version

0.1.0

**Comment by chrisbenincasa** [comment]
Yea so currently the server is not configured to serve static assets out of just `images/`. It will only look at `images/uploads/`:

https://github.com/chrisbenincasa/tunarr/blob/main/server/src/server.ts#L249

`/images` is actually served out of the server resources folder, which is separate from the "config" and not meant to be public (these are internal resources that the server expects to always exist). 

https://github.com/chrisbenincasa/tunarr/blob/main/server/src/server.ts#L253

**Comment by josway** [comment]
Understood! Thanks!
