### ISSUE TITLE
[Bug]: Guide Page Shows Channels in Order Created Not Numbered

### ISSUE THREAD

**Issue by josway** [chrisbenincasa/tunarr#548]
### What happened?

When creating a channel out of numbered order the Channels Page shows the channels in number order but the Guide Page shows them in order as created. 

### Version

0.1.0

**Comment by chrisbenincasa** [comment]
Should be a simple fix to sort this by number instead like the other API: https://github.com/chrisbenincasa/tunarr/blob/main/server/src/api/guideApi.ts#L46-L47
