### ISSUE TITLE
Detect browser wakeup and re-fetch

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#57]
When I open my laptop in the morning my guide page typically looks like this:
<img width="1897" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/daad9a71-ee73-4249-a16d-5f04ef49cb01">

If I stay on the page it just stays like this. We coulddddd use the existing setInterval on the page to store the last time setInterval ran, then compare it to the current time and if its more than an hour we do a refetch.

Need to think on a good solution here but it would be nice for it to work when:
1.) User re-opens their laptop after a long while
2.) If the guide page stays open for hours, it continually refreshes the guide page.  This would allow some users to have a dedicated "guide" screen if they wanted.

**Comment by chrisbenincasa** [comment]
IIRC react-query has this kinda stuff built in. I thought it worked automatically but maybe we need to change some query client settings.

**Comment by markdavella** [comment]
Ah yea, I do recall them having a staleness duration param.  We could probably pass in the guide duration value into that and have it auto fetch new data every time the guide duration expires

**Comment by markdavella** [comment]
I think I got this working using React Query's 'refetchInterval' set to the guide duration.  Doing some testing on it now

**Comment by markdavella** [comment]
Fixed in https://github.com/chrisbenincasa/tunarr/pull/65
