### ISSUE TITLE
Use main TV show Poster artwork instead of using Episode artwork

### ISSUE THREAD

**Issue by Keysersose12** [chrisbenincasa/tunarr#655]
For movies the Poster artwork displays fine for me in Plex but the same can't be said for TV Shows. In Plex it just seems to use a a landscape episode artwork for any poster related to the TV Show and seems to use the same episode artwork for all episodes. In comparison to the Poster artwork for Movies, the TV show artwork looks bad. The TV show artwork is displayed fine in Tunarr itself.

Instead of using episode artwork in Plex, would it be possible to have an option if using Plex to pull the main Poster artwork for the TV show instead and display that in all cases where artwork is being displayed for that TV Show (e.g. Guide, What's On, DVR Schedule and Browse views).

**Comment by chrisbenincasa** [comment]
I like the idea! Thanks!

**Comment by chrisbenincasa** [comment]
That's a great point. They're usually a different aspect ratio too which just adds to the weirdness. I'm thinking perhaps it should be the default to use the show poster
