### ISSUE TITLE
[Bug]: Artwork not loading in Plex on Windows using Tunarr Windows build

### ISSUE THREAD

**Issue by Keysersose12** [chrisbenincasa/tunarr#656]
### What happened?

I'm using Plex on Windows along with a windows build of Tunarr, and no artwork is being displayed in the Live TV section of Plex. On review of the xmltv file i noticed the links to the artwork all start like this "<icon src="{{host}}/....". If I manually replace {{host}} with the actual http localhost address that tunarr is running on in the xml file, the artwork will display properly in Plex. The artwork is displayed correctly in Tunarr itself without any modifications.

Note: I am just running the exe file by opening it and not running any particular command to run it from command prompt if that could be related to the issue.

### Version

0.2.0

### What browser did you experience the the problem on?

Chrome 127.0.6533.74

### What operating system are you using?

Windows 10

**Comment by chrisbenincasa** [comment]
The raw XMLTV file will not have the host filled in. It is filled dynamically when the XMLTV is requested via the Tunarr API. The XMLTV file should always be read via the API because of this.

Relevant code: https://github.com/chrisbenincasa/tunarr/blob/dev/server/src/api/index.ts#L183

**Comment by chrisbenincasa** [comment]
Is there a reason that you need to access the xmltv file on the filesystem directly? If the images are not showing in Plex, it sounds like there is another issue. I'd double-check the output of the xmltv file when requesting it via the API via the endpoint: `http://TUNARR_IP:PORT/api/xmltv.xml`

**Comment by Keysersose12** [comment]
Thanks, i was incorrectly thinking that I had to link the folder where the xmltv file was being saved. Works fine now using the tunarr IP. Thank you.

**Comment by chrisbenincasa** [comment]
Sorry for the confusion! Made a note on my end to call this out in the docs.
