### ISSUE TITLE
[Bug]: Error updating channel. "Zodios: Invalid Body parameter 'body'"

### ISSUE THREAD

**Issue by marshallandy83** [chrisbenincasa/tunarr#688]
### Contact Details

marshallandy83@gmail.com

### What happened?

When attempting to save changes from the Channels>Edit screen, an error is shown stating "Error updating channel. Check browser console for details".

The browser console shows an error:

```
Error: Zodios: Invalid Body parameter 'body'
    at F6e.request (index-c6d43532.js:325:9596)
    at async RN.interceptRequest (index-c6d43532.js:330:779)
    at async B6e.request (index-c6d43532.js:330:4794)Caused by: ZodError
    at get error (index-c6d43532.js:321:23047)
    at F6e.request (index-c6d43532.js:325:9649)
    at async RN.interceptRequest (index-c6d43532.js:330:779)
    at async B6e.request (index-c6d43532.js:330:4794) ZodError
    at get error (index-c6d43532.js:321:23047)
    at F6e.request (index-c6d43532.js:325:9649)
    at async RN.interceptRequest (index-c6d43532.js:330:779)
    at async B6e.request (index-c6d43532.js:330:4794) "Zodios: Invalid Body parameter 'body'"
```

### Version

0.5.3

### What browser did you experience the the problem on?

Chrome 127.0.6533.120

### What operating system are you using?

Windows 11

### Relevant log output

```shell
Nothing logged to tunarr console.
```

**Comment by chrisbenincasa** [comment]
Saw this recently with somebody in discord, though I thought we solved it. Are you using watermarks?

**Comment by marshallandy83** [comment]
Yeah this particular channel has a watermark, but even attempting to remove the watermark results in the same error. I'll delete and re-add the channel without a watermark as a workaround.

**Comment by chrisbenincasa** [comment]
I see. I will see if I can get some extra logging in there like I’ve added
on some other paths in order to figure out which field is giving a problem.

**Comment by marshallandy83** [comment]
I'm getting the same error when attempting to save after adding a filler list to a channel (channel has no watermark).

**Comment by chrisbenincasa** [comment]
I can repro the filler collection. Still not sure about the other one yet.

**Comment by chrisbenincasa** [comment]
Have an idea what's going on with filler lists and have a potential fix in place locally. Should be able to continue tonight though. Sorry for the inconvenience!

**Comment by chrisbenincasa** [comment]
I have a bunch of fixes included in https://github.com/chrisbenincasa/tunarr/pull/689

**Comment by chrisbenincasa** [comment]
These fixes are included in the 0.6.0 release, which is going out now. Once that's available, please give it another try and let me know if you have any issues! I have also included additional logging statements on this path so if you do hit another issue, we should be able to diagnose it more quickly than before. Thanks!

**Comment by marshallandy83** [comment]
Yeah seems to have resolved those issues - thanks for the quick turnaround!

**Comment by chrisbenincasa** [comment]
Awesome! Glad to hear it. Thanks for reporting, too!
