### ISSUE TITLE
ARM64 support?

### ISSUE THREAD

**Issue by GrandUpheaval** [chrisbenincasa/tunarr#719]

**Comment by chrisbenincasa** [comment]
More context: the docker ARM image generation had a bug where it would clobber the x64 one. I think I have to do some magic to have a multi arch build from GH actions

As for the binaries. I have a base binary built, I just haven't hooked up the jobs yet.

**Comment by chrisbenincasa** [comment]
d7fada412a7321dcc6648132e0d2827cf370f77d adds the builds back for Docker
8a23182ebc1b7f4f0c604584236be9eaa171d0b1 adds the binary release for ARMv8

they should land in the next version, or the upcoming edge builds
