### ISSUE TITLE
Show Custom Shows as Shows in Time Slots

### ISSUE THREAD

**Issue by sloothy420** [chrisbenincasa/tunarr#785]
**Is your feature request related to a problem? Please describe.**
Its possible. Ive created two custom shows for a channel. One has a bunch of movies and the other has a bunch of single episodes from different shows. Ive added the custom shows i created and all of the other tv shows i want for the channel and then choose Time Slots. The custom shows do not show up in the drop down for shows. Rather, the single episodes from different shows i referenced shows up as all of those different shows and the movies do no show up at all. 

**Describe the solution you'd like**
Id like for these custom shows to show up as their own show in the drop down so that their individual weights can be tweaked just like any other show with a time slot. This would be for for both Time Slots and Random Slots. For example, I have a custom show called "Halloween Movies" and another called "Halloween Specials" which has the single episodes from different shows. When choosing time slots for a channel, and then choosing "Halloween Movies" into a timeslot, it adds all the movies as episodes of a single show, so that the weights and order can be tweaked. Same with the "Halloween Specials" where id ideally shuffle the episodes and have them play more often etc etc. 

**Describe alternatives you've considered**
Not that i can think of related to this.

**Additional context**
Dizque did have this functionality built into its timeslots function as well for reference.

**Comment by chrisbenincasa** [comment]
Thanks for codifying in a bug! Funny enough, I have a TODO in the code just for this, haha: https://github.com/chrisbenincasa/tunarr/blob/dev/shared/src/services/timeSlotService.ts#L122
