### ISSUE TITLE
./tunarr.sh: 5: shift: can't shift that many Error

### ISSUE THREAD

**Issue by Bradisverycool** [chrisbenincasa/tunarr#814]
I got ./tunarr.sh: 5: shift: can't shift that many when running. Can you fix this error please. Thank You

**Comment by chrisbenincasa** [comment]
Is this resolved? What happened?

**Comment by Bradisverycool** [comment]
let me reopen it

**Comment by chrisbenincasa** [comment]
No worries. Is this macOS? Or Linux?

**Comment by Bradisverycool** [comment]
linux mint

**Comment by chrisbenincasa** [comment]
Thanks, I'll take a look.

**Comment by chrisbenincasa** [comment]
Should be fixed in 0.12.1
