### ISSUE TITLE
Not able to retreive TV playlists.

### ISSUE THREAD

**Issue by clrksml** [chrisbenincasa/tunarr#819]
I'm running into an issue with Tunarr where it refuses to get playlists for TV library. I can get Movie playlists but not TV playlists.

Version: 0.12.1
FFMPEG: 7.0
NodeJS: 20.17.0

I've tried re-installing cleanly with @latest and @edge-nvidia. Re-adding channels. Re-adding Plex server. Recreating the playlists. Validating my Plex token. Nothing has worked. Finally decided to post it here. 

![image](https://github.com/user-attachments/assets/cb974286-1f25-43ab-bfe9-b5b3b212812f)
![image](https://github.com/user-attachments/assets/b5958289-2815-40f0-a431-15bf159f45ab)
![image](https://github.com/user-attachments/assets/5ef590d5-0a68-4fa6-a11f-04d0bddb02af)

 Meanwhile in dizqueTV no issues.
![image](https://github.com/user-attachments/assets/488136da-bcc6-40e0-932e-1bc46437342a)

**Comment by clrksml** [comment]
Clean debug log
[tunarr.log](https://github.com/user-attachments/files/17196010/tunarr.log)

**Comment by chrisbenincasa** [comment]
Thanks for the thorough report and logs. Should be an easy update to make frame rate optional.
