### ISSUE TITLE
Timed (and other) slots are missing options in the programme menu

### ISSUE THREAD

**Issue by EmilMoe** [chrisbenincasa/tunarr#839]
**Is your feature request related to a problem? Please describe.**
It seems I'm missing options under "Programme" at any type of slots. I mostly see only Flex, sometimes 1 or 2 other collections/lists. I can't quiet figure out if I need to do something to refresh the cache?

**Describe the solution you'd like**
Added some playlists and series, only Flex and 1 other is showing up.

**Describe alternatives you've considered**
I can't see where I can do something different here.

**Comment by chrisbenincasa** [comment]
Hey thanks for the report! I think this is a dupe of https://github.com/chrisbenincasa/tunarr/issues/825 which I'm actively working on

**Comment by EmilMoe** [comment]
> Hey thanks for the report! I think this is a dupe of #825 which I'm actively working on

Thanks
