### ISSUE TITLE
Unable to delete a non-empty channel

### ISSUE THREAD

**Issue by bricas** [chrisbenincasa/tunarr#852]
Create a channel and add some programming, if you try to delete it, you'll see this error:

```
Error while attempting to delete channel 19c6622b-762f-4fab-9cfa-ac331050bfb1: {"code":"SQLITE_CONSTRAINT_FOREIGNKEY","name":"ForeignKeyConstraintViolationException"}
```

If you remove programming, the delete succeeds.

**Comment by chrisbenincasa** [comment]
Should be fixed with https://github.com/chrisbenincasa/tunarr/pull/889 -- released on 0.14.0
