### ISSUE TITLE
Style A-Z Filter

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#870]
We should improve styling for A-Z and increase margin from side bar as some browers overlay the scroll bar onto the filter.

Example:
<img width="728" alt="image" src="https://github.com/user-attachments/assets/9bd20719-0fa1-4a01-816a-db1be988822d">

**Comment by chrisbenincasa** [comment]
Fixed in https://github.com/chrisbenincasa/tunarr/pull/903?
