### ISSUE TITLE
HW accelerated Tunarr containers do not exist

### ISSUE THREAD

**Issue by ameturpoet** [chrisbenincasa/tunarr#886]
I'm trying to change the image tag for my Tunarr container in the Synology Docker client, but neither `ghcr.io/chrisbenincasa/tunarr:latest-vaapi` nor `chrisbenincasa/tunarr:latest-vaapi` seem to exist in the repos. Only the vanilla software-only images seem to exist. Were these images removed?

**Comment by chrisbenincasa** [comment]
I see them:

https://hub.docker.com/layers/chrisbenincasa/tunarr/latest-vaapi/images/sha256-96e25b4dae008805a7c61c14fccabc6ecd561352cadaa05688788f8ad3cd1f94?context=explore

https://github.com/chrisbenincasa/tunarr/pkgs/container/tunarr/292642394?tag=latest-vaapi

**Comment by ameturpoet** [comment]
> I see them:
> 
> https://hub.docker.com/layers/chrisbenincasa/tunarr/latest-vaapi/images/sha256-96e25b4dae008805a7c61c14fccabc6ecd561352cadaa05688788f8ad3cd1f94?context=explore
> 
> https://github.com/chrisbenincasa/tunarr/pkgs/container/tunarr/292642394?tag=latest-vaapi

I still see an error saying that it doesn't exist, I'm not sure what the issue might be: 
![image](https://github.com/user-attachments/assets/4415eb03-1ea8-4049-b41c-88ef4d1d1885)

**Comment by chrisbenincasa** [comment]
Are you running an ARM based machine?

Also if you are on macOS do you need vaapi?

**Comment by chrisbenincasa** [comment]
(Just judging from the UI could be wrong)

**Comment by chrisbenincasa** [comment]
Gotcha. Maybe an explicit pull is needed somehow? Not familiar with Synology's interface or nuances... i've successfully pulled both the docker hub and ghcr images to confirm that they're available (just now)

**Comment by hcooper** [comment]
@ameturpoet you might just need to add the repository (e.g. https://hub.docker.com/r/chrisbenincasa/tunarr)...

![image](https://github.com/user-attachments/assets/4e439cfb-4e2d-43e6-8148-9153645d8003)

**Comment by chrisbenincasa** [comment]
Ah thanks for chiming in @hcooper - that looks probable!

**Comment by chrisbenincasa** [comment]
Going to close this since I think it is stale. If adding the repository doesn't work, you can reopen and we can explore further.
