### ISSUE TITLE
minor issue with new ffmpeg stack on .16

### ISSUE THREAD

**Issue by pavlov70** [chrisbenincasa/tunarr#974]
Hi,

After upgrading to .16 and trying out the new ffmpeg stack, it seems to work quite well from initial impressions, perhaps loading a bit faster. The one issue I've encountered is when playing back via Kodi's iptv plugin. It would immediately fail without opening the stream. The log showed:
CCurlFile::Open - <http://192.168.1.135:8000/stream/channels/1fa17176-a81c-495c-a631-67a375320412.ts> Failed with code 500:

Pasting the url into vlc also resulted in failed playback. By changing the .ts to .m3u8 I was able to play back in vlc successfully, so I edited the channels.m3u and changed each .ts instance to .m3u8. This restored my kodi iptv functionality.

I should note that the above is not necessary using the old ffmpeg stack. Thanks again as always!

**Comment by chrisbenincasa** [comment]
Any relevant logs on the server side?

**Comment by chrisbenincasa** [comment]
Also can you provide a few more details? Like are you using hw accel? If so, which kind?

**Comment by chrisbenincasa** [comment]
I was able to reproduce this. Will have a fix today. Thanks for testing!

**Comment by pavlov70** [comment]
Sorry I didn't get you the logs earlier, life interrupted me. Thanks for identifying the cause and I'm looking forward to the fix.

Been using the docker vaapi and load times in Kodi are in the ~1-2 second range with the new ffmpeg changes (down a second or so). Every bit as fast as traditional linear tv!
